# Generated by Django 2.1.5 on 2020-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200821_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='question',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
